cd $(dirname $0)

cat << 'END'
//ADVNTURE JOB (SYS),'ADVENTURE',CLASS=A,
//       MSGCLASS=A,REGION=4096K,
//       USER=IBMUSER,PASSWORD=SYS1
//CLEANUP EXEC PGM=IDCAMS
//SYSIN    DD *
  DELETE SYSGEN.ADVENT
  SET MAXCC=0
//SYSPRINT DD SYSOUT=*
//ADVNT360 EXEC PL1LFC,
//  PARM.PL1L='EXTDIC,SIZE=999999,OPT=02,STMT,LOAD,NODECK'
//PL1L.SYSLIN DD DSNAME=&&LOADSET,DISP=(MOD,PASS),UNIT=SYSDA,
//  SPACE=(80,(900,100))
//PL1L.SYSIN DD *
END

cat ADVNT360.PL1

echo

cat << 'END'
/*
//ADVNTRDU EXEC FORTHC,
//  PARM.FORT='MAP,NODECK,LOAD'
//FORT.SYSLIN DD DSNAME=&&LOADSET,DISP=(MOD,PASS)
//FORT.SYSIN  DD *
END

cat ADVNTRDU.F90

echo

cat << 'END'
/*
//ADVNTTIM EXEC ASMFC,
//  PARM.ASM='NODECK,LOAD'
//ASM.SYSGO DD DSN=&&LOADSET,DISP=(MOD,PASS)
//ASM.SYSIN DD *
END

cat ADVNTTIM.hlasm

echo

cat << 'END'
/*
//ADVNTWYL EXEC ASMFC,
//  PARM.ASM='NODECK,LOAD'
//ASM.SYSGO DD DSN=&&LOADSET,DISP=(MOD,PASS)
//ASM.SYSIN DD *
END

cat ADVNTWYL.hlasm

echo

cat << 'END'
/*
//LKED     EXEC LKED,
//  PARM.LKED='LIST,XREF',
//  COND.LKED=(8,LT)
//LKED.SYSLIN  DD DSN=&&LOADSET,DISP=(OLD,DELETE)
//             DD DDNAME=SYSIN
//LKED.SYSLMOD DD DSN=SYS2.CMDLIB,DISP=SHR <<< CHECK DSNAME
//LKED.SYSLIB  DD DSN=SYSC.PL1LIB,DISP=SHR
//LKED.SYSIN   DD *
  NAME ADVNTURE(R)
/*
//CAVES    EXEC PGM=PDSLOAD
//STEPLIB  DD  DSN=SYSC.LINKLIB,DISP=SHR
//SYSPRINT DD  SYSOUT=*
//SYSUT2   DD  DSN=SYSGEN.ADVENT,DISP=(NEW,CATLG),
//             VOL=SER=PUB001,
//             UNIT=3390,SPACE=(TRK,(44,14,17)),
//             DCB=(RECFM=FB,LRECL=80,BLKSIZE=19040)
//SYSUT1   DD  DATA,DLM=@@
./ ADD NAME=CAVES    0101-21120-21120-1735-00027-00011-00000-IBMUSER 28
END
cat ADVNTCAV.TXT
echo '@@'

cat << 'END'
//CAVES    EXEC PGM=PDSLOAD
//STEPLIB  DD  DSN=SYSC.LINKLIB,DISP=SHR
//SYSPRINT DD  SYSOUT=*
//SYSUT2   DD  DSN=SYS1.CMDPROC,DISP=SHR
//SYSUT1   DD  *
./ ADD NAME=ADVENT
END

cat ADVENT.clist
echo
echo "/*"
echo "//"